### ISSUE TITLE
newest snapshot works only with LOGGING = DEBUG

### ISSUE THREAD

**Issue by stixif** [mr-manuel/venus-os_dbus-serialbattery#31] opened 2024-05-30 19:51 UTC
### Describe the bug

does not connect to venusOS

### How to reproduce

LOGGING = INFO

### Expected behavior

LOGGING = DEBUG

### Driver version

1.3.20240527dev

### Venus OS device type

Raspberry Pi 3

### Venus OS version

v3.32

### BMS type

Smart BMS (LLT, JBD, Overkill Solar)

### Cell count

18

### Battery count

2

### Connection type

Serial USB adapter to RS485

### Config file

```ini
LOGGING = DEBUG
```

### Relevant log output

```shell
no...
```

**Comment by mr-manuel** [comment] 2024-05-30 20:11
I cannot reproduce that. How did you install/update?

**Comment by mr-manuel** [comment] 2024-05-30 20:21
Fixed with `v1.3.20240530dev`. Thank you for reporting!

**Closed by mr-manuel** 2024-05-30 20:21 UTC
Labels: bug
