### ISSUE TITLE
Strange behavior with Seplos Battery 

### ISSUE THREAD

**Issue by KoljaWindeler** [mr-manuel/venus-os_dbus-serialbattery#73] opened 2024-08-26 11:47 UTC
### Describe the problem

Hi Mr-Manuel, 
i've added a third battery to my setup yesterday, this time a Seplos.
Everything worked well with serialbattery but there are some odd effects that I can't figure out.

It is very possible that this has nothing to do with serialbattery but who knows:
1. Battery is found and datacommunicatio is working fine 
![image](https://github.com/user-attachments/assets/94253bc5-43b4-44c4-aeed-a90723ad19ac)
2. But the menu at Settings -> System Settings -> Battery measurements  is NOT showing the new battery
![image](https://github.com/user-attachments/assets/7c5cd6ad-7fbf-4808-b622-cf04fe3d5f08)
I've update the driver, rebooted the system .. nothing .. ok whatever .. not important 
3. my Homeassistant setup was also NOT receiving any MQTT updates from the new battery. 
... which was strange, because I had a JKBMS Inverter BMS connected to the system before and didn't change the setup since.

dbus-spy is showing all the as victronenergy.battery.* 
![image](https://github.com/user-attachments/assets/60be989f-f15f-438b-a783-08a45060ee90)

and I'm subscribing to all c06*****1fe4/battery/# topics but I'm not getting any update from battery/3/# as I get it from battery/2/# 

any idea why? likely not connected to this driver or? 
Thanks Kolja

### Driver version of the currently installed driver

v1.3.20240705

### Venus OS device type

Raspberry Pi

### Venus OS version

v3.30

### BMS type

Seplos

### Cell count

16

### Battery count

3

### Connection type

Serial USB adapter to RS485

### Config file

```ini
default
```

### Relevant log output

```shell
@4000000066cc69cc29238844 INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000066cc69cc292b63fc INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000066cc69cc293406ec INFO:SerialBattery:> MIN CELL VOLTAGE: 2.900 V | MAX CELL VOLTAGE: 3.450 V| FLOAT CELL VOLTAGE: 3.375 V
@4000000066cc69cc293c28f4 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 100.0 A | MAX BATTERY DISCHARGE CURRENT: 100.0 A
@4000000066cc69cc29442004 INFO:SerialBattery:> CVCM:     True
@4000000066cc69cc294c1afc INFO:SerialBattery:> CCCM CV:  True  | DCCM CV:  True
@4000000066cc69cc29541dc4 INFO:SerialBattery:> CCCM T:   True  | DCCM T:   True
@4000000066cc69cc295bfd64 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: False
@4000000066cc69cc2964179c INFO:SerialBattery:> CHARGE FET: None | DISCHARGE FET: None | BALANCE FET: None
@4000000066cc69cc296d33a4 INFO:SerialBattery:Serial Number/Unique Identifier: SeplosBMS16cells_280.0Ah
```

**Comment by KoljaWindeler** [comment] 2024-08-26 12:27
1. nope, but good idea .. will try later today
2. yes :) 
3. yep - no change
4. 2 / 1 / 5 (seplos) I've also check all other devices and they all have different ID's

**Comment by KoljaWindeler** [comment] 2024-08-26 13:15
ok .. strange .. 1. worked .. seplos only ,.. after that also all other batteries worked .. no idea what happened here but works now.
thanks for your idea :)

**Comment by KoljaWindeler** [comment] 2024-08-27 04:45
Actually .. the Battery monitor still doesn't work .. no idea why but I can't get my Seplos battery in the menu.
Everything else is working fine now .. This is really not important for me, it is just strange :D 
I have a JKBMS incoming, will see if that shows up or if there is some kind of limitations to only show the first two or so

**Comment by KoljaWindeler** [comment] 2024-11-26 13:59
hi, I'd like to bring this up again .. as the new gui is also not showing the seplos batteries .. 

to summarize: my setup has 4 jkbms_pb, all connected via one rs485 but and 2 seplos batteries (both on the second rs485 bus).
All batteries show up in the old UI (/gui-v1/) device overview:
![image](https://github.com/user-attachments/assets/9dde9aae-bd76-4248-8d5f-1bb81966de6d)

in the old ui I can NOT change the visibility of the seplos batteries in the sub menu -> settings -> system setup -> battery measurements 
![image](https://github.com/user-attachments/assets/e9394cb7-d8d3-4e3e-b5cb-22678f68dcaf)
there is no scrolling down any further

I've also tried with only the seplos batteries connected (one) .. same result .. no seplos battery available.
I've also tried with the nightly build .. also no change 

please check the IDs below
![image](https://github.com/user-attachments/assets/1cbbf0bb-6ce4-4514-ab3c-72d56d39eea4)


it is not a critical issue because everything important works but it is sad that the batteries are not showing up online and on the new GUI 
![image](https://github.com/user-attachments/assets/2ea0f159-25b3-4f4e-adfc-70cec42fba9a)


any idea how to debug this? I've checked with dbus-spy and the only "interesting" part was the serial that is "_dev_ttyUSB1__0x01" for the seplos .. is that a possibility?

**Comment by mr-manuel** [comment] 2024-11-26 19:13
Can you write me on Discord so I can check your system?

**Comment by KoljaWindeler** [comment] 2024-11-26 19:36
Sure, let me know how .. I feel old now .. not a discord guy ;)

**Comment by mr-manuel** [comment] 2024-11-26 20:11
You find the link in my profile. Anyway I was able to reproduce it. Somehow.

Checking the code of the QML page this relies on this dbus path: `com.victronenergy.system/AvailableBatteries`

This dbus path is populated by https://github.com/victronenergy/dbus-systemcalc-py/blob/17965bb50e21b2218a26a4768385896caab2983f/delegates/batterydata.py#L276-L304

<details><summary>The data of my testsetup:</summary>

```
root@einstein:~# dbus -y com.victronenergy.system /AvailableBatteries GetValue
('{"com.victronenergy.battery/3": {"name": "SerialBattery(JKBMS PB CAN)", '
 '"channel": null, "type": "battery"}}')

root@einstein:~# dbus -y com.victronenergy.system /AvailableBatteryMeasurements GetValue
{'com_victronenergy_battery_1/Dc/0': 'SerialBattery(JKBMS) on Serial '
                                     '/dev/ttyUSB0',
 'com_victronenergy_battery_3/Dc/0': 'SerialBattery(JKBMS CAN V2) on CAN can0 '
                                     'Device address 0',
 'default': 'Automatic',
 'nobattery': 'No battery monitor'}

root@einstein:~# dbus -y com.victronenergy.system /AvailableBatteryServices GetValue
('{"default": "Automatic", "nobattery": "No battery monitor", '
 '"com.victronenergy.battery/3": "SerialBattery(JKBMS CAN V2) on CAN can0 '
 'Device address 0", "com.victronenergy.battery/1": "SerialBattery(JKBMS) on '
 'Serial /dev/ttyUSB0"}')

root@einstein:~# dbus -y com.victronenergy.system /AvailableBmsServices GetValue
[{'instance': 3, 'name': 'SerialBattery(JKBMS PB CAN)'},
 {'instance': 1, 'name': 'SerialBattery(JKBMS)'}]
 
root@einstein:~# dbus -y com.victronenergy.system /Batteries GetValue
[{'active_battery_service': False,
  'bmsstate': 14,
  'current': 0.0,
  'id': 'com.victronenergy.battery.can0',
  'instance': 3,
  'name': 'SerialBattery(JKBMS PB CAN)',
  'power': 0.0,
  'soc': 87,
  'state': 0,
  'temperature': 1.0,
  'voltage': 13.1},
 {'active_battery_service': True,
  'bmsstate': 9,
  'current': -0.0,
  'id': 'com.victronenergy.battery.ttyUSB0',
  'instance': 1,
  'name': 'SerialBattery(JKBMS)',
  'power': -0.0,
  'soc': 87,
  'state': 0,
  'temperature': 22.0,
  'voltage': 13.17}]
```

</details>

<details><summary>The data of your setup:</summary>

```
dbus -y com.victronenergy.system /AvailableBatteries GetValue
('{"com.victronenergy.vebus/291": {"name": "MultiPlus-II 48/5000/70-50", '
 '"channel": null, "type": "vebus"}, "com.victronenergy.battery/17": {"name": '
 '"SB 4 JKBMS", "channel": null, "type": "battery"}, '
 '"com.victronenergy.battery/18": {"name": "SB 1 JKBMS ", "channel": null, '
 '"type": "battery"}, "com.victronenergy.battery/19": {"name": "SB 6 JKBMS", '
 '"channel": null, "type": "battery"}, "com.victronenergy.battery/20": '
 '{"name": "SB 5 JKBMS", "channel": null, "type": "battery"}, '
 '"com.victronenergy.battery/0": {"name": "AggregateBatteries", "channel": '
 'null, "type": "battery"}, "com.victronenergy.battery/15": {"name": "SB 3 '
 'Seplos", "channel": null, "type": "battery"}, '
 '"com.victronenergy.battery/16": {"name": "SB 2 Seplos", "channel": null, '
 '"type": "battery"}}')

dbus -y com.victronenergy.system /AvailableBatteryMeasurements GetValue
{'com_victronenergy_battery_0/Dc/0': 'AggregateBatteries on Virtual',
 'com_victronenergy_battery_15/Dc/0': 'SerialBattery(Seplos) on Serial '
                                      '/dev/ttyUSB1__0x01',
 'com_victronenergy_battery_16/Dc/0': 'SerialBattery(Seplos) on Serial '
                                      '/dev/ttyUSB1__0x02',
 'com_victronenergy_battery_17/Dc/0': 'SerialBattery(JKBMS PB Model) on Serial '
                                      '/dev/ttyUSB0__0x01',
 'com_victronenergy_battery_18/Dc/0': 'SerialBattery(JKBMS PB Model) on Serial '
                                      '/dev/ttyUSB0__0x02',
 'com_victronenergy_battery_19/Dc/0': 'SerialBattery(JKBMS PB Model) on Serial '
                                      '/dev/ttyUSB0__0x03',
 'com_victronenergy_battery_20/Dc/0': 'SerialBattery(JKBMS PB Model) on Serial '
                                      '/dev/ttyUSB0__0x04',
 'com_victronenergy_vebus_291/Dc/0': 'MultiPlus-II 48/5000/70-50 on VE.Bus',
 'default': 'Automatic',
 'nobattery': 'No battery monitor'}

dbus -y com.victronenergy.system /AvailableBatteryServices GetValue
('{"default": "Automatic", "nobattery": "No battery monitor", '
 '"com.victronenergy.vebus/291": "MultiPlus-II 48/5000/70-50 on VE.Bus", '
 '"com.victronenergy.battery/17": "SerialBattery(JKBMS PB Model) on Serial '
 '/dev/ttyUSB0__0x01", "com.victronenergy.battery/18": "SerialBattery(JKBMS PB '
 'Model) on Serial /dev/ttyUSB0__0x02", "com.victronenergy.battery/19": '
 '"SerialBattery(JKBMS PB Model) on Serial /dev/ttyUSB0__0x03", '
 '"com.victronenergy.battery/20": "SerialBattery(JKBMS PB Model) on Serial '
 '/dev/ttyUSB0__0x04", "com.victronenergy.battery/0": "AggregateBatteries on '
 'Virtual", "com.victronenergy.battery/15": "SerialBattery(Seplos) on Serial '
 '/dev/ttyUSB1__0x01", "com.victronenergy.battery/16": "SerialBattery(Seplos) '
 'on Serial /dev/ttyUSB1__0x02"}')

dbus -y com.victronenergy.system /AvailableBmsServices GetValue
[{'instance': 17, 'name': 'SB 4 JKBMS'},
 {'instance': 18, 'name': 'SB 1 JKBMS '},
 {'instance': 19, 'name': 'SB 6 JKBMS'},
 {'instance': 20, 'name': 'SB 5 JKBMS'},
 {'instance': 0, 'name': 'AggregateBatteries'},
 {'instance': 15, 'name': 'SB 3 Seplos'},
 {'instance': 16, 'name': 'SB 2 Seplos'}]

dbus -y com.victronenergy.system /Batteries GetValue

[{'active_battery_service': False,
  'bmsstate': 9,
  'current': -2.69,
  'id': 'com.victronenergy.battery.ttyUSB0__0x01',
  'instance': 17,
  'name': 'SB 4 JKBMS',
  'power': -142.85,
  'soc': 85,
  'state': 2,
  'temperature': 19.1,
  'timetogo': 173793,
  'voltage': 53.1},
 {'active_battery_service': False,
  'bmsstate': 9,
  'current': -2.69,
  'id': 'com.victronenergy.battery.ttyUSB0__0x02',
  'instance': 18,
  'name': 'SB 1 JKBMS ',
  'power': -142.87,
  'soc': 85,
  'state': 2,
  'temperature': 20.0,
  'timetogo': 170677,
  'voltage': 53.11},
 {'active_battery_service': False,
  'bmsstate': 9,
  'current': -1.52,
  'id': 'com.victronenergy.battery.ttyUSB0__0x03',
  'instance': 19,
  'name': 'SB 6 JKBMS',
  'power': -80.68,
  'soc': 89,
  'state': 2,
  'temperature': 18.2,
  'timetogo': 301046,
  'voltage': 53.08},
 {'active_battery_service': False,
  'bmsstate': 9,
  'current': -1.53,
  'id': 'com.victronenergy.battery.ttyUSB0__0x04',
  'instance': 20,
  'name': 'SB 5 JKBMS',
  'power': -81.02,
  'soc': 88,
  'state': 2,
  'temperature': 18.65,
  'timetogo': 265580,
  'voltage': 53.1},
 {'active_battery_service': True,
  'current': -16.5,
  'id': 'com.victronenergy.battery.aggregate',
  'instance': 0,
  'name': 'AggregateBatteries',
  'power': -875.9575000000001,
  'soc': 86.38324769452421,
  'state': 2,
  'temperature': 19.041666666666668,
  'voltage': 53.08833333333334}]
```

</details>

I have to investigate further...

**Comment by mr-manuel** [comment] 2024-12-05 14:30
While troubleshooting the problem solved itself. Since then we were not able to reproduce it again. I will close this issue again.

**Closed by mr-manuel** 2024-12-05 14:30 UTC
Labels: support
